export const GET_CURRENTWEATHER = 'GET_CURRENTWEATHER';
export const GET_ONECALL = 'GET_ONECALL';
export const SET_STORED_CURRENTWEATHER = 'SET_STORED_CURRENTWEATHER';
export const SET_STORED_ONECALL = 'SET_STORED_ONECALL';
